### ISSUE TITLE
Fired arrows don't stack

### ISSUE THREAD

**Issue by Picajoluna** [WalrusNetwork/bugs#13]
Arrows that have been fired don't retain the 'item NBT' status, unlike those found in player inventories -- meaning the two do not stack in inventories.

I also don't know if fired arrows can stack amongst one another, although I'd assume that they can.

**Comment by Siceth** [comment]
Fired arrows definitely stack. The question is, should spawned arrows _not_ have a tag or should ground arrows have a tag? I'm assuming the former?

**Comment by mitchts** [comment]
Arrows that have NBT have it because of the `death-drop` attribute. This is so the plugin knows that the item should/should not be dropped on death.

Maybe a better alternative to how this is currently handled is to do something similar to item remove and just filter the material. This way it's just a global filter for everything and not decided per item stack. I cannot think of a case where this will cause bad behaviour.

**Comment by mattarnold98** [comment]
@mitchts I've added a <death-drop> filter in the same vein as the item remove filter. I'm thinking we should keep the current death-drop attribute as well, just in case there are any edge cases, but in general using that filter should solve this.

**Comment by dustinn1** [comment]
Should be good with the `<death-drop>` filter.
