### ISSUE TITLE
Server not up straight away

### ISSUE THREAD

**Issue by mattarnold98** [WalrusNetwork/bugs#19]
DNS propagation issue, just delay the discord announcement message around 5 seconds to allow time for the DNS to propagate.

**Comment by Siceth** [comment]
big brain alternative: make a new subdomain for every potential player and then virtualhost-route it until dns propagates /s

**Comment by Picajoluna** [comment]
There's also this from unixfox in pub Discord, #development:

> unixfoxToday at 9:06 AM
I don't know anything about your internal architecture but why don't you guys a wildcard domain instead of adding a domain on the fly?
Like instead of generating automatically a domain like that: thisisaserver.walrus.gg.
Just add a wildcard for *.dynamicserver.walrus.gg and use this sub domain as a way to generate random sub domain like thisisaserver.dynamicserver.walrus.gg
It will requires to use a bungeecord that can redirect based on the hostname and having a wildcard for each region.
Bungeecord is even not required you may just develop a skeleton "hub" Minecraft server that its only function is to redirect to a Minecraft server based on the hostname.
*.us-east.walrus.gg
*.us-west.walrus.gg
*.eu.walrus.gg
*.asia.walrus.gg
This way you don't have to wait for the DNS propagation and you don't have to pay an extra public IPv4 address each time a server is deployed.
That's what epicube, an old popular Minecraft server did when deploying a private server dynamically.

**Comment by Indicardo** [comment]
That wouldn't be much convenient. We don't pay extra for IPv4's since once we're done with them they are probably used somewhere else by the host.

We could get the IP on start and subsequently create the DNS record while the server itself is creating. It would allow for more time to propagate correctly

**Comment by unixfox** [comment]
The ultimate solution is to add the IP to the record just after the server gets created.

**Comment by Indicardo** [comment]
> The ultimate solution is to add the IP to the record just after the server gets created.

Already implemented in Snout. Closing this issue
